version: '3.9'

services:
  check:
    build: .
    container_name: check_app
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - check_db
      - redis
    env_file:
      - .env

  check_db:
    image: postgres:15.2
    container_name: check_db_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env


  nginx:
    image: nginx:1.21.4-alpine
    container_name: nginx
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - static_value:/var/html/static/

      - media_value:/var/html/media/

    depends_on:
      - check

  redis:
    restart: always
    image: redis:7.0.5-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  worker:
    restart: always
    container_name: celery_worker
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  beat:
    restart: always
    container_name: celery_beat
    build: .
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  static_value:
  media_value: