# Generated by Django 4.2.4 on 2023-08-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadedfile_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_state',
            field=models.CharField(choices=[('new', 'New'), ('reload', 'Reload')], default='new', max_length=10),
        ),
    ]
